# Dependencies
markdown:         kramdown
highlighter:      rouge

#dirs
tag_dir: tag

# Setup
title:            pentalpha blog
tagline:          A personal blog on Bioinformatics (PT-BR and ENG-US)
description:      "A personal blog on bioinformatics and other things // Um blog pessoal incluindo, entre outras coisas, tutoriais sobre bioinformática"
url:              http://pentalpha.github.io/
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           Pitágoras Alves
  url:            https://twitter.com/_pentalpha

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://github.com/pentalpha/pentalpha.github.io
